version: '3'
services:
  web:
    build: .
    environment: [
      "GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}",
      "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}",
      "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}"
    ]
    ports:
      - "3103:3103"
