version: '3'
services:
  web:
    build: .
    environment: [
      "GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}",
      "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}",
      "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
    ]
    ports:
      - "3103:3103"
